### ISSUE TITLE
How to run your program

### ISSUE THREAD

**Issue by jonico** [FelixNeutatz/GitHubRepositoryClassifier#4]
Hi @kevinkepp and @FelixNeutatz. From your ```README.md``` it is not really clear which of the steps are absolutely required to classify our golden data set. Are the extractor / attachment download steps optional or mandatory?  We do not like to do any training but just run a single command where to put in the file as input. Providing a docker image / virtual appliance or hosted web site where your program is already running would be optimal. The other solutions evaluated so far could be setup within minutes and the longest one took about 60 minutes to complete the classification of the 221 repositories we test with (with one token). Hearing that the Linux kernel (which is among the samples) already takes 12 hours may not make the evaluation of your solution suitable for most jury members. On the other hand we really love your documentation and would be thrilled to see your accuracy / precision on our data. If there was any way for you to provide us a setup where we do not have to specify 20 parameters, run many programs and have to wait multiple days before we see a result, you are still in the game  (provided that your solution has great accuracy / precision)👍 

Best, Johannes

**Comment by FelixNeutatz** [comment]
Hi Johannes,

first, a quick tutorial how to set everything up:
1) setup Maven
```
git clone https://github.com/FelixNeutatz/GitHubRepositoryClassifier.git
cd GitHubRepositoryClassifier
mvn clean install
```
2) setup Python
```
cd GitHubRepositoryClassifier/model
/usr/bin/python2.7 setup.py install
```
3) configure GitHub token
 Now create a file, e.g. "/path/mygittoken.txt". Then you enter the generated token in the following way (without brackets):
```
oauth=[my GitHub access token]
```
Then create a file "/path/tokenfilelist.csv" which contains all the token files like this:
```
/path/mygittoken.txt
/path/mygittoken2.txt
...
```
Now you specify this file in `../GitHubRepositoryClassifier/commons/src/main/resources/conf/conf.properties`:
```
sample.generation.git-accounts.file=/path/tokenfilelist.csv
```
4) run classification:
```
cd GitHubRepositoryClassifier/model/ml
/usr/bin/python2.7 classify.py --input golden_data_set.csv
```

To your other questions: extractor / attachment download steps are optional and only required for training / validation.

About the time constraint: 
For every repository we download up to 10k issues, 10k commits, 10k releases, 10k branches, 10k languages, 10k contributors and some more statistics.
Given a rate limit of 5000 requests per hour we calculate here the number of requests for the linux repository alone:
10.000 commits (100 requests)
1 branch (1 request)
497 releases (5 requests)
6 languages (1 request)
more than 100 contributors (1 request)

So if we have a lot of big repositories the program will not run through in an hour. We can change the our limit to 1000 elements per category (issues, commits,...) but this would probably reduce the quality of the predictions since we trained on unlimited issues, ...

What should we do?
Fixing the limit is super easy we just change this line: https://github.com/FelixNeutatz/GitHubRepositoryClassifier/blob/master/serialization/src/main/java/tu/kn/ghrepoclassifier/serialization/data/RepoData.java#L79

Of course, you could also add some more authentication tokens to speed up downloading.

Best regards,
Felix & Kevin

**Comment by jonico** [comment]
Thanks @FelixNeutatz, your running instruction are now much clearer to us. We will probably give you the benefit of the doubt and assume you classify the linux repo correctly and only categorize the way smaller 220 Git repos.

**Comment by kevinkepp** [comment]
Hi @jonico, we [commited](https://github.com/jonico/tu-berlin-evaluation/commit/851968e21cbf5bd38b111615e28d9dc6260cf005) the predictions the of our algorithm on the golden data set in the tu-berlin-evaluation repository. We used 5 API tokens and it took the program one night to download and classify the repositories.
Best, 
Kevin & Felix

**Comment by jonico** [comment]
> Hi @jonico, we commited the predictions the of our algorithm on the golden data set in the tu-berlin-evaluation repository. We used 5 API tokens and it took the program one night to download and classify the repositories.

Thank you!
